package tn.esprit.wayfinder.data

/**
 * Dictionnaire centralisé pour les traductions français-anglais
 * Utilisé pour changer dynamiquement la langue de l'application
 */
object LanguageDictionary {
    
    private val dictionary = mapOf(
        // Navigation
        "Accueil" to "Home",
        "Favoris" to "Favorites",
        "Discussions" to "Discussions",
        "Profil" to "Profile",
        
        // Profile
        "Profil" to "Profile",
        "Modifier le profil" to "Edit profile",
        "Se déconnecter" to "Logout",
        "It's Your Profiles" to "It's Your Profiles",
        "Your Bio auto generated by Gemini" to "Your Bio auto generated by Gemini",
        "Partager mon voyage" to "Share my journey",
        "Historique des réservations" to "Booking history",
        "Voir les voyages partagés" to "View shared journeys",
        "Apparence" to "Appearance",
        "Mode sombre" to "Dark mode",
        "Dark mode" to "Dark mode",
        "Light mode" to "Light mode",
        "Suivre le thème système" to "Follow system theme",
        "Le thème suit les paramètres système" to "Theme follows system settings",
        "Le thème est défini manuellement" to "Theme is set manually",
        "Thème sombre activé" to "Dark theme enabled",
        "Thème clair activé" to "Light theme enabled",
        "Mes favoris" to "My favorites",
        "Mes itinéraires" to "My itineraries",
        "Notifications" to "Notifications",
        "Historique de recherche" to "Search history",
        "Alertes de prix" to "Price alerts",
        "Destinations hors ligne" to "Offline destinations",
        "My Memories" to "My Memories",
        
        // Language
        "Langue" to "Language",
        "Français" to "French",
        "Anglais" to "English",
        "Sélectionner la langue" to "Select language",
        
        // Home
        "Bienvenue" to "Welcome",
        "Personnalisé par Gemini" to "Personalized by Gemini",
        "Voyages adaptés à vos préférences" to "Trips tailored to your preferences",
        "Comparateur avec Gemini" to "Comparator with Gemini",
        "Voir tous" to "See all",
        "Destinations recommandées" to "Recommended destinations",
        "Voir plus" to "See more",
        "Préférences" to "Preferences",
        "Europe" to "Europe",
        "Asie" to "Asia",
        "Amerique" to "America",
        "Australie" to "Australia",
        "Salut" to "Hi",
        "Bonjour" to "Good morning",
        "Bon après-midi" to "Good afternoon",
        "Bonsoir" to "Good evening",
        "Prêt pour votre prochaine aventure?" to "Ready for your next adventure?",
        "Explorateur" to "Explorer",
        "Aucune destination disponible" to "No destinations available",
        "Discussions de la communauté" to "Community discussions",
        "Partagez vos expériences et découvrez les conseils des voyageurs" to "Share your experiences and discover travelers' tips",
        "Créez vos Reels WayFinder" to "Create your WayFinder Reels",
        "Transformez vos voyages en Reels captivants et publiez-les automatiquement sur Instagram" to "Transform your travels into captivating Reels and publish them automatically on Instagram",
        "Affichage hors ligne (cache)" to "Offline display (cache)",
        "Réessayer" to "Retry",
        
        // Favorites
        "Aucun favori pour le moment" to "No favorites yet",
        "Mes favoris" to "My favorites",
        "Erreur" to "Error",
        "Ajoutez des destinations à vos favoris\npour les retrouver facilement" to "Add destinations to your favorites\nto find them easily",
        "Retirer des favoris" to "Remove from favorites",
        "Aucun favori" to "No favorites",
        
        // Discussions
        "Discussions" to "Discussions",
        "Aucune discussion pour le moment" to "No discussions yet",
        "Créer la première discussion" to "Create the first discussion",
        "Créer une discussion" to "Create discussion",
        "Titre" to "Title",
        "Contenu" to "Content",
        "Destination (optionnel)" to "Destination (optional)",
        "Publier" to "Publish",
        "Annuler" to "Cancel",
        "Ouvrir" to "Open",
        "Charger plus" to "Load more",
        "Commentaires" to "Comments",
        "Aucun commentaire pour le moment" to "No comments yet",
        "Ajoutez un commentaire..." to "Add a comment...",
        "Répondre" to "Reply",
        "Aimer" to "Like",
        
        // Login / Signup
        "Bienvenue sur Wayfindr" to "Welcome to Wayfindr",
        "Veuillez vous connecter pour commencer" to "Please login to get started",
        "Nom d'utilisateur ou email" to "Username or email",
        "Mot de passe" to "Password",
        "Se connecter" to "Login",
        "Pas de compte ?" to "No account?",
        "Mot de passe oublié ?" to "Forgot password?",
        "OU" to "OR",
        "Google" to "Google",
        "S'inscrire" to "Sign up",
        "Powered by Gemini" to "Powered by Gemini",
        
        // Booking
        "Réservations" to "Bookings",
        "Réservation" to "Reservation",
        "Historique des réservations" to "Booking history",
        "Détails de la réservation" to "Booking details",
        "Réserver" to "Book",
        "Réserver à nouveau" to "Book again",
        "Date dépassée" to "Date passed",
        "Confirmer" to "Confirm",
        "Annuler" to "Cancel",
        "Impossible de charger les détails du vol sélectionné. Veuillez revenir aux résultats." to "Unable to load selected flight details. Please go back to results.",
        "Compagnie inconnue" to "Unknown airline",
        "Départ :" to "Departure:",
        "Retour :" to "Return:",
        "Informations de paiement" to "Payment information",
        "Numéro de carte" to "Card number",
        "Nom sur la carte" to "Name on card",
        "Expiration" to "Expiration",
        "CVV" to "CVV",
        "Résumé" to "Summary",
        "Prix du vol" to "Flight price",
        "Taxes" to "Taxes",
        "Bagages & services" to "Baggage & services",
        "Total" to "Total",
        "Confirmer la réservation" to "Confirm reservation",
        
        // Journeys
        "Partager mon voyage" to "Share my journey",
        "Partagez vos photos et créez une vidéo" to "Share your photos and create a video",
        "Vérification en cours..." to "Checking...",
        "Vous devez avoir une réservation confirmée" to "You must have a confirmed booking",
        "Voir les voyages partagés" to "View shared journeys",
        "Voyages partagés" to "Shared journeys",
        "Aucun voyage partagé" to "No shared journeys",
        "Soyez le premier à partager !" to "Be the first to share!",
        "Description" to "Description",
        "Tags" to "Tags",
        "Images" to "Images",
        "Destination" to "Destination",
        "Sélectionner des images" to "Select images",
        "Télécharger" to "Upload",
        "Modifier" to "Edit",
        "Supprimer" to "Delete",
        
        // Reviews
        "Avis" to "Reviews",
        "Ajouter un avis" to "Add a review",
        "Aucun avis pour le moment. Soyez le premier à laisser un avis!" to "No reviews yet. Be the first to leave a review!",
        "Modifier votre avis" to "Edit your review",
        "Note" to "Rating",
        "Commentaire (optionnel)" to "Comment (optional)",
        "Publier" to "Publish",
        
        // General
        "Chargement..." to "Loading...",
        "Erreur" to "Error",
        "Réessayer" to "Retry",
        "Enregistrer" to "Save",
        "Retour" to "Back",
        "Oui" to "Yes",
        "Non" to "No",
        "OK" to "OK",
        
        // Notifications
        "Notifications" to "Notifications",
        "Aucune notification" to "No notifications",
        
        // Search
        "Rechercher" to "Search",
        "Historique de recherche" to "Search history",
        "Aucun historique" to "No history",
        
        // Itinerary
        "Mes itinéraires" to "My itineraries",
        "Créer un itinéraire" to "Create itinerary",
        "Détails de l'itinéraire" to "Itinerary details",
        "Retour" to "Back",
        "Nouvel itinéraire" to "New itinerary",
        "Aucun itinéraire" to "No itinerary",
        "Créez votre premier itinéraire de voyage" to "Create your first travel itinerary",
        "Public" to "Public",
        "jour" to "day",
        "jours" to "days",
        "planifié" to "planned",
        "planifiés" to "planned",
        
        // Settings
        "Paramètres" to "Settings",
        "À propos" to "About",
        "Déconnexion" to "Logout",
        
        // Flight details
        "Détails du vol" to "Flight details",
        "Compagnie aérienne" to "Airline",
        "Durée" to "Duration",
        "Prix" to "Price",
        "Alerte prix" to "Price alert",
        "Télécharger pour hors ligne" to "Download for offline",
        "Équipements disponibles" to "Available amenities",
        "Comparer les prix" to "Compare prices",
        "Réserver" to "Book",
        "ensoleillé" to "sunny",
        "Resto" to "Restaurant",
        "Wi-Fi gratuit" to "Free Wi-Fi",
        "Café" to "Cafe",
        "Affaires" to "Business",
        
        // Travel tips
        "Conseils de voyage" to "Travel tips",
        "Impossible de charger les conseils" to "Unable to load tips",
        "Générer les conseils" to "Generate tips",
        "Voir tout" to "See all",
        
        // Payment
        "Paiement" to "Payment",
        "Paiement PayPal" to "PayPal payment",
        "Erreur PayPal" to "PayPal error",
        "Veuillez réessayer." to "Please try again.",
        
        // Chat
        "Chat - Packs" to "Chat - Packs",
        "Consulter Gemini" to "Consult Gemini",
        "Bonjour! J'ai préparé 3 packs pour vous, lequel préférez-vous?" to "Hello! I've prepared 3 packs for you, which one do you prefer?",
        "Ou, proposez-moi vos idées!" to "Or, suggest your ideas!",
        
        // Errors
        "Une erreur est survenue" to "An error occurred",
        "Impossible de charger les données" to "Unable to load data",
        "Connexion échouée" to "Connection failed",
        "Vérifiez votre connexion Internet" to "Check your Internet connection",
        
        // Success messages
        "Opération réussie" to "Operation successful",
        "Enregistré avec succès" to "Saved successfully",
        "Supprimé avec succès" to "Deleted successfully",
        
        // Empty states
        "Aucun résultat" to "No results",
        "Aucune donnée disponible" to "No data available",
        
        // Profile content
        "It's Your Profiles" to "Your Profile",
        "Email" to "Email",
        "Téléphone" to "Phone",
        "Ajouter un numéro" to "Add a number",
        "Localisation" to "Location",
        "Ajouter une localisation" to "Add a location",
        "Your Bio auto generated by Gemini" to "Your bio auto-generated by Gemini",
        "Ajoutez une bio pour aider Gemini à personnaliser vos recommandations de voyage." to "Add a bio to help Gemini personalize your travel recommendations.",
        "213 Photos" to "213 Photos",
        "1,123 Save Post" to "1,123 Saved Posts",
        
        // Booking confirmation
        "Vérification en cours..." to "Checking...",
        "Vous devez avoir une réservation confirmée" to "You must have a confirmed booking",
        
        // Video generation
        "Générer une vidéo" to "Generate video",
        "Génération en cours..." to "Generating...",
        "Vidéo prête" to "Video ready",
        "Erreur de génération" to "Generation error",
        
        // Date formats
        "aujourd'hui" to "today",
        "hier" to "yesterday",
        "il y a" to "ago",
        "jour" to "day",
        "jours" to "days",
        "mois" to "month",
        "mois" to "months",
        "année" to "year",
        "années" to "years",
        
        // All Flights Screen
        "Tous les vols" to "All flights",
        "Filtrer par région" to "Filter by region",
        "Filtres avancés" to "Advanced filters",
        "Tous" to "All",
        "Résultats hors ligne (cache)" to "Offline results (cache)",
        "Mode hors ligne" to "Offline mode",
        "Aucun vol disponible" to "No flights available",
        "pour la région sélectionnée" to "for the selected region",
        "Réinitialiser" to "Reset",
        "Fermer" to "Close",
        "Prix" to "Price",
        "Compagnie aérienne" to "Airline",
        "Aucune compagnie disponible" to "No airlines available",
        "Durée maximale" to "Maximum duration",
        "heures" to "hours",
        "Classe de voyage" to "Travel class",
        "Économique" to "Economy",
        "Premium Économique" to "Premium Economy",
        "Affaires" to "Business",
        "Première" to "First",
        "Appliquer les filtres" to "Apply filters",
        "Remove from favorites" to "Remove from favorites",
        "Add to favorites" to "Add to favorites",
        
        // Share Journey Screen
        "Partager mon voyage" to "Share my journey",
        "Astuce" to "Tip",
        "Sélectionnez vos meilleures photos de voyage pour les partager avec la communauté." to "Select your best travel photos to share with the community.",
        "Photos du voyage" to "Travel photos",
        "Add Images" to "Add Images",
        "Ajouter des photos" to "Add photos",
        "Jusqu'à 20 photos" to "Up to 20 photos",
        "Add More" to "Add More",
        "Remove" to "Remove",
        "Destination du voyage" to "Travel destination",
        "Chargement des réservations..." to "Loading bookings...",
        "Erreur de chargement" to "Loading error",
        "Aucune réservation confirmée" to "No confirmed bookings",
        "Vous devez avoir une réservation confirmée pour partager votre voyage." to "You must have a confirmed booking to share your journey.",
        "Aucune destination trouvée dans les réservations" to "No destination found in bookings",
        "Vos réservations confirmées n'ont pas de destination spécifiée. Veuillez mettre à jour vos réservations." to "Your confirmed bookings don't have a specified destination. Please update your bookings.",
        "Sélectionnez votre destination" to "Select your destination",
        "Sélectionnez une destination" to "Select a destination",
        "Confirmation:" to "Confirmation:",
        "Date:" to "Date:",
        "⚠️ Destination non spécifiée" to "⚠️ Destination not specified",
        "⚠️ Cette réservation n'a pas de destination spécifiée. Le système utilisera le nom de la réservation comme destination." to "⚠️ This booking doesn't have a specified destination. The system will use the booking name as destination.",
        "Description (optionnel)" to "Description (optional)",
        "Décrivez votre voyage..." to "Describe your trip...",
        "Tags (optionnel)" to "Tags (optional)",
        "Ex: plage, montagne, culture (séparés par des virgules)" to "Ex: beach, mountain, culture (separated by commas)",
        "Compression:" to "Compression:",
        "Upload:" to "Upload:",
        
        // Journey Feed Screen
        "Voyages partagés" to "Shared journeys",
        "Aucun voyage partagé" to "No shared journeys",
        "Soyez le premier à partager !" to "Be the first to share!",
        "Vidéos par destination" to "Videos by destination",
        "Tous les voyages" to "All trips",
        "photos" to "photos",
        "Générer" to "Generate",
        "Échec" to "Failure",
        "Video generation failed:" to "Video generation failed:",
        "Step:" to "Step:",
        
        // Booking History Screen
        "Historique des réservations" to "Booking history",
        "Voici vos dernières réservations" to "Here are your latest bookings",
        "Aucune réservation" to "No bookings",
        "Confirmed" to "Confirmed",
        "Pending" to "Pending",
        "Cancelled" to "Cancelled",
        
        // Notifications Screen
        "Notifications" to "Notifications",
        "Tout marquer comme lu" to "Mark all as read",
        "Supprimer toutes les notifications" to "Delete all notifications",
        "Supprimer toutes les notifications ?" to "Delete all notifications?",
        "Êtes-vous sûr de vouloir supprimer toutes les notifications ? Cette action est irréversible." to "Are you sure you want to delete all notifications? This action is irreversible.",
        "Confirmer" to "Confirm",
        "Aucune notification" to "No notifications",
        "Vous n'avez pas de notifications pour le moment" to "You have no notifications at the moment",
        "Supprimer" to "Delete",
        "À l'instant" to "Just now",
        "min" to "min",
        "h" to "h",
        "j" to "d",
        
        // Notification Types and Messages
        "Réservation confirmée" to "Booking confirmed",
        "Réservation confirmée!" to "Booking confirmed!",
        "Votre réservation a été confirmée avec succès. Vous recevrez un email de confirmation sous peu." to "Your reservation has been successfully confirmed. You will receive a confirmation email shortly.",
        "Voir mes réservations" to "View my reservations",
        "Retour à l'accueil" to "Return to home",
        "Total payé" to "Total paid",
        "Statut" to "Status",
        "Confirmé" to "Confirmed",
        "Destination" to "Destination",
        "Réservation annulée" to "Booking cancelled",
        "Réservation mise à jour" to "Booking updated",
        "Paiement réussi" to "Payment successful",
        "Échec du paiement" to "Payment failed",
        "Alerte de prix" to "Price alert",
        "votre destination" to "your destination",
        "Numéro de confirmation" to "Confirmation number",
        "Votre réservation pour" to "Your reservation for",
        "a été confirmée" to "has been confirmed",
        "a été annulée" to "has been cancelled",
        "a été mise à jour" to "has been updated",
        "Votre paiement de" to "Your payment of",
        "a été effectué avec succès" to "has been processed successfully",
        "Le paiement de" to "The payment of",
        "a échoué" to "failed",
        "Veuillez réessayer" to "Please try again",
        "Le prix pour" to "The price for",
        "a baissé de" to "has dropped by",
        "Nouveau prix" to "New price",
        
        // Social Notifications (Posts and Journeys)
        "Votre post a été aimé" to "Your post was liked",
        "a aimé votre post" to "liked your post",
        "Nouveau commentaire sur votre post" to "New comment on your post",
        "a commenté votre post" to "commented on your post",
        "Votre voyage a été aimé" to "Your journey was liked",
        "a aimé votre voyage à" to "liked your journey to",
        "Nouveau commentaire sur votre voyage" to "New comment on your journey",
        "a commenté votre voyage à" to "commented on your journey to",
        "Quelqu'un" to "Someone",
        
        // Search History Screen
        "Historique de recherche" to "Search history",
        "Effacer tout" to "Clear all",
        "Récent" to "Recent",
        "Enregistrés" to "Saved",
        "Aucune recherche récente" to "No recent searches",
        "Aucune recherche enregistrée" to "No saved searches",
        "Vos recherches récentes apparaîtront ici" to "Your recent searches will appear here",
        "Enregistrez des recherches pour y accéder rapidement" to "Save searches to access them quickly",
        
        // Price Alerts Screen
        "Alertes de prix" to "Price alerts",
        "Ajouter une alerte" to "Add alert",
        "Actives uniquement" to "Active only",
        "Aucune alerte de prix" to "No price alerts",
        "Créez une alerte pour être notifié lorsque le prix change" to "Create an alert to be notified when the price changes",
        "Prix cible" to "Target price",
        "Prix actuel" to "Current price",
        "Alerte si prix ≤" to "Alert if price ≤",
        
        // Offline Destinations Screen
        "Destinations hors ligne" to "Offline destinations",
        "Supprimer tout" to "Delete all",
        "Aucune destination hors ligne" to "No offline destinations",
        "Téléchargez des destinations depuis leur page de détails pour les consulter hors ligne" to "Download destinations from their detail page to view them offline",
        
        // Edit Profile Screen
        "Modifier le profil" to "Edit profile",
        "Prénom" to "First name",
        "Nom" to "Last name",
        "Téléphone" to "Phone",
        "Localisation" to "Location",
        "Bio" to "Bio",
        "Préférences de voyage" to "Travel preferences",
        "Sélectionnez vos intérêts pour des recommandations personnalisées" to "Select your interests for personalized recommendations",
        "Enregistrer" to "Save",
        "Profil mis à jour avec succès!" to "Profile updated successfully!",
        
        // Journey Feed Screen
        "Aucun voyage partagé" to "No shared journeys",
        "Soyez le premier à partager votre voyage !" to "Be the first to share your journey!",
        "Vidéos par destination" to "Videos by destination",
        "Tous les voyages" to "All trips",
        "photos" to "photos",
        "Générer" to "Generate",
        "Échec" to "Failure",
        "Video generation failed:" to "Video generation failed:",
        "Step:" to "Step:",
        "Supprimer le voyage" to "Delete journey",
        "Êtes-vous sûr de vouloir supprimer ce voyage ? Cette action est irréversible." to "Are you sure you want to delete this journey? This action is irreversible.",
        "Désactiver" to "Deactivate",
        "Activer" to "Activate",
        "Expire le:" to "Expires on:",
        "Déclenché le:" to "Triggered on:",
        "Type:" to "Type:",
        "Vidéo AI générée" to "AI generated video",
        "Génération de la vidéo en cours..." to "Video generation in progress...",
        "Une vidéo AI sera automatiquement générée avec vos photos et de la musique !" to "An AI video will be automatically generated with your photos and music!",
        "Régénérer la vidéo" to "Regenerate video",
        "Générer ma vidéo" to "Generate my video",
        "Lecture de la vidéo:" to "Playing video:",
        "Erreur:" to "Error:",
        "Sélectionnez vos intérêts pour des recommandations personnalisées" to "Select your interests for personalized recommendations",
        "Vidéo prête" to "Video ready",
        "Génération en cours..." to "Generation in progress...",
        "Vidéo non générée" to "Video not generated",
        "Détails de l'erreur" to "Error details",
        "La génération de la vidéo a échoué. Détails de l'erreur :" to "Video generation failed. Error details:",
        "Vidéo de test non disponible. Configurez un service de génération vidéo." to "Test video not available. Configure a video generation service.",
        "Impossible de charger la vidéo. Vérifiez votre connexion Internet." to "Unable to load video. Check your Internet connection.",
        "Serveur vidéo indisponible" to "Video server unavailable",
        "Erreur de connexion réseau" to "Network connection error",
        "Format vidéo non supporté" to "Unsupported video format",
        "Erreur de lecture" to "Playback error",
        "Le chargement de la vidéo prend trop de temps" to "Video loading is taking too long",
        "URL vidéo invalide" to "Invalid video URL",
        "Erreur de chargement" to "Loading error",
        
        // Comments section
        "Commentaires" to "Comments",
        "commentaires" to "comments",
        "commentaire" to "comment",
        "Commentaire" to "Comment",
        "Aucun commentaire pour le moment" to "No comments for the moment",
        "Ajoutez un commentaire..." to "Add a comment...",
        "Ajouter un commentaire..." to "Add a comment...",
        
        // Flight Details Screen
        "Détails du vol" to "Flight details",
        "Informations du vol" to "Flight information",
        "Départ" to "Departure",
        "Arrivée" to "Arrival",
        "Compagnie aérienne" to "Airline",
        "Durée" to "Duration",
        "À propos" to "About",
        "Destination surprise" to "Surprise destination",
        "À définir" to "To be defined",
        "Impossible de charger les détails depuis la sélection précédente." to "Unable to load details from previous selection.",
        "Téléchargé - Supprimer" to "Downloaded - Remove",
        "Téléchargement..." to "Downloading...",
        "Télécharger pour hors ligne" to "Download for offline",
        "Alerte prix" to "Price alert",
        "Réserver" to "Book",
        "N/A" to "N/A",
        
        // Travel Tips Screen
        "Conseils de voyage" to "Travel tips",
        "Tous" to "All",
        "Général" to "General",
        "Transport" to "Transport",
        "Hébergement" to "Accommodation",
        "Nourriture" to "Food",
        "Culture" to "Culture",
        "Sécurité" to "Safety",
        "Budget" to "Budget",
        "Météo" to "Weather",
        "Aucun conseil disponible" to "No tips available",
        "Les conseils seront générés automatiquement" to "Tips will be generated automatically",
        "Voir tout →" to "See all →",
        "Impossible de charger les conseils" to "Unable to load tips",
        "Générer les conseils" to "Generate tips",
        "Génération des conseils..." to "Generating tips...",
        "Voir tout →" to "See all →",
        
        // Create Itinerary Screen
        "Nouvel itinéraire" to "New itinerary",
        "Titre de l'itinéraire *" to "Itinerary title *",
        "Description" to "Description",
        "Destination *" to "Destination *",
        "Date de début *" to "Start date *",
        "Date de fin *" to "End date *",
        "Budget total" to "Total budget",
        "Rendre cet itinéraire public" to "Make this itinerary public",
        "Créer l'itinéraire" to "Create itinerary"
    )
    
    /**
     * Traduit un texte du français vers la langue cible
     * @param text Le texte en français à traduire
     * @param targetLanguage La langue cible ("en" pour anglais, "fr" pour français)
     * @return Le texte traduit, ou le texte original si la traduction n'existe pas
     */
    fun translate(text: String, targetLanguage: String): String {
        return if (targetLanguage == "en") {
            dictionary[text] ?: text
        } else {
            // Pour le français, on cherche la traduction inverse
            dictionary.entries.find { it.value.equals(text, ignoreCase = true) }?.key ?: text
        }
    }
    
    /**
     * Traduit un texte du français vers l'anglais
     */
    fun toEnglish(frenchText: String): String {
        return dictionary[frenchText] ?: frenchText
    }
    
    /**
     * Traduit un texte de l'anglais vers le français
     */
    fun toFrench(englishText: String): String {
        return dictionary.entries.find { it.value.equals(englishText, ignoreCase = true) }?.key ?: englishText
    }
    
    /**
     * Vérifie si une traduction existe pour un texte donné
     */
    fun hasTranslation(text: String, targetLanguage: String): Boolean {
        return if (targetLanguage == "en") {
            dictionary.containsKey(text)
        } else {
            dictionary.values.any { it.equals(text, ignoreCase = true) }
        }
    }
}
